version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/alardin-back-test/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/dev-run.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/health_check.sh
      timout: 300
      runas: ec2-user