version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/alardin-back-test/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: ec2-user
  AfterAllowTestTraffic: "arn:aws:lambda:ap-northeast-2:985013825538:function:alardin-back-deploy-notoion"