services:
  api:
    stdin_open: true
    tty: true
    build: 
      dockerfile: Dockerfile
      context: .

      target: production

    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    network_mode: host

    command: npm run start:dev
    ports:
      - 3000:3000