version: '3.9'

services:
  api-dev:
    depends_on:
      - redis
    build: 
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - 3000:3000

  api-prod:
    build: 
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    network_mode: host
    ports:
      - 3000:3000
  redis:
    container_name: cache
    image: redis
    ports:
    - 6379:6379
    volumes:
    - /Users/jobyeong-geun/redis:/data

volumes:
  redis:
    driver: local



    