services:
  api:
    build: 
      dockerfile: Dockerfile
      context: .
      target: production
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - 3000:3000