version: '3.9'

services:
  dev:
    build: 
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    network_mode: host
    ports:
      - 3000:3000

  prod:
    build: 
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    network_mode: host
    ports:
      - 3000:3000


    