version: '3.9'

services:
  api:
    build: 
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - DB_HOST=10.1.143.164
    ports:
      - 3000:3000

    