FROM node:16-alpine As install

WORKDIR /usr/src/app

COPY --chown=node:node package*.json .

RUN npm install

COPY --chown=node:node . .

USER node

FROM node:16-alpine As migration

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

COPY --chown=node:node --from=install /usr/src/app/node_modules ./node_modules
COPY  --chown=node:node . .

USER node

RUN npm run migrate:run

