version: '3.9'

services:
  migrations:
    build: 
      dockerfile: docker/Dockerfile.migrations
      context: ..
      target: migration
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    network_mode: host
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-group: "alardin-back-log"
    #     awslogs-region: "ap-northeast-2"
    #     awslogs-stream: "db-migrations"

