version: '3.9'

services:
  api-dev:
    build: 
      dockerfile: ../docker/Dockerfile
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - 3000:3000

  api-prod:
    build: 
      dockerfile: ../docker/Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    network_mode: host
    ports:
      - 3000:3000
    logging:
      driver: awslogs
      options:
        awslogs-group: "alardin-back-log"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "backend-nestjs"

