version: '3.9'

services:
  api-dev:
    build: 
      dockerfile: docker/Dockerfile
      context: ..
      target: development
    command: npm run start:dev
    env_file:
      - ../.dev.env
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - 3000:3000

  api-prod:
    image: ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${IMAGE_TAG}
    container_name: ${DOCKER_APP_NAME}-${IMAGE_TAG}
    volumes:
      - .:/usr/src/app
      - /home/ec2-user/firebase:/home/node/firebase
    env_file:
      - ../.env
    network_mode: host
    ports:
      - 3000:3000
    logging:
      driver: awslogs
      options:
        awslogs-group: "alardin-back-log"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "backend-nestjs"
  api-test:
    depends_on:
      - redis
    image: ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${IMAGE_TAG}
    container_name: ${DOCKER_APP_NAME}-${IMAGE_TAG}
    env_file:
      - ../.env
    network_mode: host
    volumes:
      - .:/usr/src/app
      #- /home/ec2-user/firebase:/usr/src/app/firebase
    ports:
      - 3000:3000
    logging:
      driver: awslogs
      options:
        awslogs-group: "alardin-back-dev"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "backend-nestjs"
  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
