# This is a basic workflow to help you get started with Actions

name: Develop deploy to EC2 and Dockerhub
# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
on:
  push:
    branches: [ "feature/ecs-test" ]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        env:
          KEY: ${{ secrets.FIREBASE_ACCOUNT }}
        run: echo "$KEY" > file.txt && cat file.txt
        shell: bash

    